name: Cypress Continuous Integration

on:
  push:
    branches:
    - '**'
  pull_request:
    branches: [ main ]

jobs:
  cypress_tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 12
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: delete cache
      run: npm cache clean --force
    - name: Install cypress
      run: npm i -g cypress
    - name: Run cypress tests
      uses: cypress-io/github-action@v2
      with:
        browser: chrome
        command: npm run test:cypress:headless